server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
spring:
  application:
    name: ticket-booking-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:rootpassword@localhost:27017/ticket_bookings?authSource=admin}
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_URI:localhost:29092}
      bindings:
        ticket-booking-out-0:
          destination: ticket-booking-topic
          group: ticket-booking-api