# invoicing-service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: invoicing-service
  name: invoicing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoicing-service
  template:
    metadata:
      labels:
        app: invoicing-service
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs.json-logging/json.keys_under_root: "true"
        co.elastic.logs.json-logging/json.add_error_key: "true"
        co.elastic.logs.json-logging/json.message_key: "message"
    spec:
      containers:
        - env:
            - name: EUREKA_URI
              value: http://service-registry:8761/eureka
            - name: KAFKA_URI
              value: http://kafka-service:9092
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              value: "true"
            - name: MANAGEMENT_HEALTH_READINESSTATE_ENABLED
              value: "true"
            - name: MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED
              value: "true"
            - name: SERVER_SHUTDOWN
              value: "graceful"
          image: aquiliz/ticketr-io:invoicing-service
          name: invoicing-service
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              port: 8082
              path: /actuator/health/liveness
          readinessProbe:
            httpGet:
              port: 8082
              path: /actuator/health/readiness
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
      restartPolicy: Always

---
# invoicing-service Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: invoicing-service
  name: invoicing-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    app: invoicing-service