name: Build and test Ticketr-io
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
          cd api-gateway
          mvn -B verify
          cd ../invoicing-service
          mvn -B verify
          cd ../service-registry
          mvn -B verify
          cd ../ticket-booking-service
          mvn -B verify
          cd ../ticket-pricing-service
          mvn -B verify